### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by jmadkins** [mythcoders/hermes#22]
The app needs to be converted to a Docker app

**Tasks**
- [x] Running in Docker
~Digital Ocean load balancer~
- [x] Traefik request routing
- [x] GitHub Actions deploying to Heroku
~Kubernets test app at `hermes.ts.mythcoders.io`~
~Kubernets staging app at `hermes.sg.mythcoders.io`~
~Kubernets prod app at `hermes.mythcoders.io`~
